org: lucasfranzolin
app: imoveis-lindoia
service: imoveis-lindoia-api
frameworkVersion: '3'

custom:
    functionsBasePath: handlers
    stages:
        - stg
        - prod

plugins:
    - serverless-plugin-typescript
    - serverless-functions-base-path
    - serverless-stage-manager

provider:
    name: aws
    runtime: nodejs16.x
    timeout: 10
    environment:
        NODE_ENV: ${opt:stage}
        ENDPOINT: ${param:ENDPOINT}
        AWS_S3_ACCESS_KEY: ${param:AWS_S3_ACCESS_KEY}
        AWS_S3_SECRET_KEY: ${param:AWS_S3_SECRET_KEY}
        AWS_S3_BUCKET_REGION: ${param:AWS_S3_BUCKET_REGION}
        AWS_S3_BUCKET_NAME: ${param:AWS_S3_BUCKET_NAME}
        MONGO_USER: ${param:MONGO_USER}
        MONGO_PASSWORD: ${param:MONGO_PASSWORD}
        MONGO_CLUSTER_NAME: ${param:MONGO_CLUSTER_NAME}
        MONGO_DB_NAME: ${param:MONGO_DB_NAME}
        MAIL_NAME: ${param:MAIL_NAME}
        MAIL_ADDRESS: ${param:MAIL_ADDRESS}
        MAIL_HOST: ${param:MAIL_HOST}
        MAIL_PORT: ${param:MAIL_PORT}
        MAIL_AUTH_USER: ${param:MAIL_AUTH_USER}
        MAIL_AUTH_PASSWORD: ${param:MAIL_AUTH_PASSWORD}
        JWT_ACCESS_TOKEN_SECRET: ${param:JWT_ACCESS_TOKEN_SECRET}
        JWT_REFRESH_TOKEN_SECRET: ${param:JWT_REFRESH_TOKEN_SECRET}
        CONFIRMATION_TOKEN_SECRET: ${param:CONFIRMATION_TOKEN_SECRET}

functions:
    api:
        handler: api.handler
        events:
            - http: ANY /
            - http: ANY /{proxy+}
